### ISSUE TITLE
排版样式上有问题

### ISSUE THREAD

**Issue by NiCools** [dream2023/f-render#49]
![image](https://user-images.githubusercontent.com/30192035/89748756-65ec8c80-daf7-11ea-947e-ae7f153119c0.png)
上面四个每个宽度为6，再拖一个宽度为6的组件，跑到最右边去了，期望应该是左边开始。如果能有行的概念就好了  现在是列，列高度比其他的列高就会出现这个问题。望作者大大解决一下，之前提过的。

**Comment by dream2023** [comment]
已解决，文档：https://www.yuque.com/chaojie-vjiel/vbwzgu/iw5dzf#OZSgf
