### ISSUE TITLE
f-render 的 select 组件的 options 属性无法指定 url。 

### ISSUE THREAD

**Issue by godcheese** [dream2023/f-render#59]
## Bug report（问题描述）
f-render 的 select 组件的 options 属性无法指定 url，参考文档[options讲解](https://www.yuque.com/chaojie-vjiel/vbwzgu/rgenav) ，配置了 :options-fn 后然后设置 options 表单设计器直接报错。

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/4585378/91418771-31adf580-e885-11ea-8c22-06878889f2a3.png)

![image](https://user-images.githubusercontent.com/4585378/91418721-1d69f880-e885-11ea-8fed-ef4852024c53.png)

#### Other relevant information（格外信息）

- Vue version:
- f-render version:4.5.0
- ElementUI version:2.13.2
- vue-ele-form version:0.8.35

**Comment by dream2023** [comment]
已解决
