### ISSUE TITLE
富文本属性配置报错

### ISSUE THREAD

**Issue by wq163** [dream2023/f-render#61]
import comps from "f-render/fixtures/comps";
	// 富文本配置
import quillEditor from "f-render/fixtures/extends/quill-editor";
富文本属性配置报错

These dependencies were not found:

* f-render/fixtures/comps in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/FormDesign.vue?vue&type=script&lang=js&
* f-render/fixtures/extends/quill-editor in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/FormDesign.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save f-render/fixtures/comps f-render/fixtures/extends/quill-editor

运行npm install --save f-render/fixtures/comps f-render/fixtures/extends/quill-editor也不行

**Comment by dream2023** [comment]
什么版本？

**Comment by dream2023** [comment]
升级到最新的试试

**Comment by dream2023** [comment]
不好意思，文档写的有问题，少了一个 src

```js
import comps from "f-render/src/fixtures/comps";
import quillEditor from "f-render/src/fixtures/extends/quill-editor";
```
