### ISSUE TITLE
规则编辑会相互影响

### ISSUE THREAD

**Issue by liangwenle** [dream2023/f-render#62]
创建多个字段，给一个字段添加规则，剩余字段也会被添加上一样的规则
删除一个规则配置，其他字段也会被删除规则配置
![Sep-04-2020 11-36-25](https://user-images.githubusercontent.com/10026149/92206393-05fcc200-eeba-11ea-8b36-97b25edb7ef3.gif)

**Comment by dream2023** [comment]
已修复
