### ISSUE TITLE
批量添加的input属性配置 会和拖拽生产的input 错乱

### ISSUE THREAD

**Issue by changxin1999** [dream2023/f-render#64]
问题描述 ： 批量添加的input属性配置会错乱   
批量添加生成的input 会 把拖拽生产的input的表单项属性配置 覆盖 （错乱）

问题复现步骤：
1. 先拖拽一个input放入展示中
2.点击批量添加  添加方式， 逐个新增  表单项 ：1 ，label：1 ，选择type：input 点击提交
3.此刻 批量添加生产的input 的 属性配置会显示 第一个拖拽生成input的配置 依次都会错乱
![1](https://user-images.githubusercontent.com/31536741/99354670-d74f8e80-28e1-11eb-9ec6-707b877de3b3.png)
![2](https://user-images.githubusercontent.com/31536741/99354676-da4a7f00-28e1-11eb-87d9-d22f204a64da.png)
![3](https://user-images.githubusercontent.com/31536741/99354682-db7bac00-28e1-11eb-961c-6664136a4564.png)
![4](https://user-images.githubusercontent.com/31536741/99354686-dd456f80-28e1-11eb-9bf1-8520d34e26f5.png)
![5](https://user-images.githubusercontent.com/31536741/99354690-df0f3300-28e1-11eb-8084-17ec7acbdf3e.png)
麻烦大佬有时间可以解决一下 谢谢了

**Comment by changxin1999** [comment]
在提一个建议 
建议把拖拽区域放大点...有点小

**Comment by dream2023** [comment]
纯数字会出现这个问题，这和对象啊类型的 key 的排序有关系

**Comment by dream2023** [comment]
拖拽区域，自己覆盖 css 样式即可

**Comment by changxin1999** [comment]
哦哦 好的 谢谢大佬解答
