### ISSUE TITLE
想问下 这个是不支持 vue2.0使用吗？ 之前的回答没了

### ISSUE THREAD

**Issue by changxin1999** [dream2023/f-render#65]
我按着文档安装  完成打开页面 提示我  Maximum call stack size exceeded  （超出了最大调用堆栈大小）
![11](https://user-images.githubusercontent.com/31536741/99357622-2c41d380-28e7-11eb-932b-5c568ace2120.png)
![22](https://user-images.githubusercontent.com/31536741/99357652-3a8fef80-28e7-11eb-998d-6f555675ad0b.png)
![33](https://user-images.githubusercontent.com/31536741/99357667-3ebc0d00-28e7-11eb-9c13-fb95617db2d6.png)

**Comment by dream2023** [comment]
我这边未能复现，你用 https://codesandbox.io/ 看看能不能复现

**Comment by changxin1999** [comment]
哦哦 可以了 我自己把 页面的name 和 组件名 重复了  不好意思了  谢谢大佬解答了
