### ISSUE TITLE
在创建表单时，同一类表单组件的placeholder属性没有单独保存

### ISSUE THREAD

**Issue by sinkcoder** [dream2023/f-render#66]
## Bug report（问题描述）
比如添加2个单行输入框，改动其中一个输入框的placeholder属性后，另一输入框的placeholder属性也会跟着变动。该问题只出现在创建表单的时候，更新表单无该问题。
#### Steps to reproduce（问题复现步骤）

1. 添加2个单行输入框
2. 修改其中1个输入框的placeholder属性

#### Other relevant information（格外信息）

- Vue version: 2.6.10
- f-render version: 4.12.1
- ElementUI version: 2.13.2
- vue-ele-form version: 0.8.53

**Comment by dream2023** [comment]
有没有 GIF

**Comment by dream2023** [comment]
已解决，请更新
