### ISSUE TITLE
select组件如何配置post请求，并且配置参数？

### ISSUE THREAD

**Issue by lishaokun** [dream2023/f-render#67]
#### Other relevant information（格外信息）

- Vue version:
- f-render version:
- ElementUI version:
- vue-ele-form version:

**Comment by dream2023** [comment]
如果不传body的话，直接 `axios.post` 传过去即可，如果传参数的话，写个方法：

```js

methods: {
  optionsFn(options) {
       // 实际返回一个函数即可
       return this.axios.post(options, { xxxx })
  }
}
```
